CREATE SEQUENCE seq_listas_pais START WITH 1 INCREMENT BY 1 nocache ;
DROP SEQUENCE seq_listas_pais;
---
CREATE SEQUENCE seq_listas_provincia_estado START WITH 1 INCREMENT BY 1 nocache ;
DROP SEQUENCE seq_listas_provincia_estado;
---
CREATE SEQUENCE seq_listas_ciudad START WITH 1 INCREMENT BY 1 nocache ;
DROP SEQUENCE seq_listas_ciudad;
---
CREATE SEQUENCE seq_listas_artista START WITH 1 INCREMENT BY 1 nocache ;
DROP SEQUENCE seq_listas_artista;
---
CREATE SEQUENCE seq_listas_genero START WITH 1 INCREMENT BY 1 nocache ;
DROP SEQUENCE seq_listas_genero;
---
CREATE SEQUENCE seq_listas_cancion START WITH 1 INCREMENT BY 1 nocache ;
DROP SEQUENCE seq_listas_cancion;
---
CREATE SEQUENCE seq_listas_lista START WITH 1 INCREMENT BY 1 nocache ;
DROP SEQUENCE seq_listas_lista;


CREATE TABLE LISTAS_PAIS(
    CODIGO NUMBER(3) DEFAULT seq_listas_pais.nextval PRIMARY KEY,
	NOMBRE VARCHAR2(50) UNIQUE
);

CREATE TABLE LISTAS_PROVINCIA_ESTADO(

    COD NUMBER(3) DEFAULT seq_listas_provincia_estado.nextval PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    COD_PAIS NUMBER(3) REFERENCES LISTAS_PAIS(CODIGO)
);

CREATE TABLE LISTAS_CIUDAD(
    COD NUMBER(3) DEFAULT seq_listas_ciudad.nextval PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    PROVINCIA_ESTADO NUMBER(3) REFERENCES LISTAS_PROVINCIA_ESTADO
);
/*La ciudad ya se relaciona con la provincia y el pais*/
CREATE TABLE LISTAS_ARTISTA(
    COD NUMBER(4) DEFAULT seq_listas_artista.nextval PRIMARY KEY,
	NOMBREARTISTICO VARCHAR2(50) UNIQUE,
    COD_CIUDAD NUMBER(3) REFERENCES LISTAS_CIUDAD(COD)

);

CREATE TABLE LISTAS_GRUPO(
    COD NUMBER(4) PRIMARY KEY,
    FCREACION DATE NOT NULL,
    FDISOLUCION DATE,
    FOREIGN KEY(COD) REFERENCES LISTAS_ARTISTA
);

CREATE TABLE LISTAS_ARTISTAIND(
    COD NUMBER(4) PRIMARY KEY, 
    nombreReal VARCHAR2(100) UNIQUE not null,
    FNAC DATE not null,
    FMUERTE DATE,
    FOREIGN KEY(COD) REFERENCES LISTAS_ARTISTA
);

CREATE TABLE LISTAS_GENERO(
    COD NUMBER(4) DEFAULT seq_listas_genero.nextval PRIMARY KEY,
	NOMBRE VARCHAR2(50) UNIQUE
);

CREATE TABLE LISTAS_CANCION(
    COD NUMBER(4) DEFAULT seq_listas_cancion.nextval PRIMARY KEY,
	TITULO VARCHAR2(50) NOT NULL,
    ANYO NUMBER(4),
    COD_ARTISTA NUMBER(4) NOT NULL,
    FOREIGN KEY(COD_ARTISTA) REFERENCES LISTAS_ARTISTA
);

CREATE TABLE LISTAS_GENERO_CANCION(
    COD_CANCION NUMBER(4),
    COD_GENERO NUMBER(4),
    PRIMARY KEY(COD_CANCION, COD_GENERO),
    FOREIGN KEY(COD_CANCION) REFERENCES LISTAS_CANCION,
    FOREIGN KEY(COD_GENERO) REFERENCES LISTAS_GENERO
);

CREATE TABLE LISTAS_LISTA(
    COD NUMBER(4) DEFAULT seq_listas_lista.nextval PRIMARY KEY,
	NOMBRE VARCHAR2(100) NOT NULL,
    ANYO NUMBER(4) NOT NULL,
    FUENTE VARCHAR2(120),
    AUTOR VARCHAR2(50)
);

/*posicion debe formar parte de la clave primaria (o poner restriccion de unica junto con lista y cancion), porque si no podrían haber posiciones repetCODas en una misma lista para diferentes canciones*/
CREATE TABLE LISTAS_POSICION_LISTA(
    COD_CANCION NUMBER(4),
    COD_LISTA NUMBER(4),
    POSICION NUMBER(4) NOT NULL UNIQUE,
    PRIMARY KEY(COD_CANCION, COD_LISTA),
    FOREIGN KEY(COD_CANCION) REFERENCES LISTAS_CANCION,
    FOREIGN KEY(COD_LISTA) REFERENCES LISTAS_LISTA
);

ALTER TABLE LISTAS_ARTISTAIND ADD CONSTRAINT MORIRDESPUES CHECK (FMUERTE>FNAC);
ALTER TABLE LISTAS_GRUPO ADD CONSTRAINT DISOLVERDESPUES CHECK (FDISOLUCION>FCREACION);
ALTER TABLE LISTAS_POSICION_LISTA ADD CONSTRAINT POSPOSITIVA CHECK (POSICION>0);
ALTER TABLE LISTAS_LISTA ADD CONSTRAINT ANYOLISTA CHECK (ANYO>0);

TRUNCATE TABLE LISTAS_CANCION;
TRUNCATE TABLE LISTAS_LISTA;
TRUNCATE TABLE LISTAS_POSICION_LISTA;

DROP TABLE LISTAS_PAIS CASCADE CONSTRAINTS;
DROP TABLE LISTAS_PROVINCIA_ESTADO CASCADE CONSTRAINTS;
DROP TABLE LISTAS_GENERO CASCADE CONSTRAINTS;
DROP TABLE LISTAS_CIUDAD CASCADE CONSTRAINTS;
DROP TABLE LISTAS_CANCION CASCADE CONSTRAINTS;
DROP TABLE LISTAS_LISTA CASCADE CONSTRAINTS;
DROP TABLE LISTAS_ARTISTA CASCADE CONSTRAINTS;
DROP TABLE LISTAS_GRUPO CASCADE CONSTRAINTS;
DROP TABLE LISTAS_ARTISTAIND CASCADE CONSTRAINTS;
DROP TABLE LISTAS_GENERO_CANCION CASCADE CONSTRAINTS;
DROP TABLE LISTAS_POSICION_LISTA CASCADE CONSTRAINTS;

